### ISSUE TITLE
Project dead?

### ISSUE THREAD

**Issue by fipsy1** [OUGC-Network/ougc-Custom-Rates#43]
Is this project dead? In myBB 1.8.33 it can't even be installed anymore. And the support page points to a download of VMware vCenter Converter Standalone.

**Comment by Sama34** [comment]
Hi, this project is certainly not dead, if you find any issue please provide enough details as to debug and then fix if the issue is found properly

Also, I'm unsure what "support page" is pointing to any "VMware vCenter Converter Standalone" as I wasn't unable to find that issue in any of the official plugin pages

**Comment by fipsy1** [comment]
The support page refers to https://ougc.network. This is then classified as dangerous by Malwarebytes. If you add an exception for this domain to Malwarebytes, the connection works, but you then get a "502 Bad Gateway" error. I have now tried it with different browsers on different computers and also from the smartphone: The page is not accessible!
